# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e0482717c76462021cd8f240b0869123831771dc1e8bf40aedd983ce5a6d862e7cf3e0a49c6b6a301e2ffd06fe8229e68a995f4af8e0072096b82b215a1bf77

test:
  secret_key_base: 0c619efc0a51abff570d5a3d489721a25b9bc6e4aec2563521a2508947e16c0b51447e2162e228b51662c765b7bd922943ad40624cb0695b2fd676da34c90384

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
